### ISSUE TITLE
Proposal for persistent --run package configuration

### ISSUE THREAD

**Issue by miha-plesko** [mikelangelo-project/capstan#3]
We could introduce a new file, `run.yaml` in 'meta' folder of the package (where package.yaml currently resides).  This new file would then contain metadata needed to run VM with this unikernel.

Content of `run.yaml` would depend on package type, e.g. for `package-type: java` it would be:

``` yaml
// run.yaml

# required run attributes
package-type: java

# type-specific run attributes
main: package1.Main
classpath:
   - /src
```

Or for `package-type: node` it would be:

``` yaml
// run.yaml

# required run attributes
package-type: node

# type-specific run attributes
main: /app.js
```

This means that capstan would need a small refactoring since parsing java.yaml is currently hard-coded.
But on the other hand we could use this same `run.py` file to store MinRam, MinHdd etc. data in it.

Thoughts?

**Comment by gberginc** [comment]
Few comments to your proposal:

- This file is not mandatory, right?
- I don't have a problem renaming `java.yaml` to `run.yaml`. I would suggest to rename `package-type` to `app-type` (or even just `runtime`). Also, the value from this property must implicitly request other packages (java, node, ...), even if the `meta/package` does not specify them.
- Do you have any suggestion for native apps, i.e. C/C++ where you normally don't need additional runtime environment such as JVM or Node server? Would this be another type (native) or would this be without the type?
- I presume the `--run` flag would override the specification in the `run.yaml`?
- What do you think about naming the run configurations? For example, if we look at HDFS app package that we have, it could be used to host the master node or the slave node. Basically, the package content is the same, most of the java settings also, apart from the difference of requesting `datanode` or `namenode`. Using _named_ run configurations would also allow one to quickly switch between the commands that were provided upfront by the package manager.
- Finally, something that is currently not supported (a matter of a different issue, I guess): run configurations should be inherited as well. Again, example with HDFS, if the HDFS package provides the run config and I create a new package with environment-specific HDFS settings, I should still be able to use the command from the required (HDFS) package.

**Comment by miha-plesko** [comment]
I'd do this for the first version of it:
* `run.yaml` would not be mandatory - without it capstan would work same as before
* I'd take `runtime` term instead of `package-type`.
  But I'm not sure if it makes sense to babysit user with automatic package loading, since eventually this will result in "Why do I need to have package.yaml then". But I know what you mean, it would make sense nevertheless so I'll go for it and implement this.
* I'd introduce a `runtime: native` to make `runtime` field required. This way it will be easier to implement and also run.yaml will be more readable.
* Regarding the named configurations I'd do it like this:

```yaml
// run.yaml (named configurations)

# required run attributes
runtime: node

# required when you opt-in for named configurations
config_set:  
   myconfig1: # <--- this is configuration name
      # runtime-specific run attributes
      main: app.js
   myconfig2:
      main: alternative.js   

# optional
config_set_default: myconfig1
```
Since I imagine that most of the users would only need a single configuration, I'd allow them to omit `config_set` key and write an unnamed configuration directly, e.g.:

```yaml
// run.yaml (single configuration)

# required run attributes
runtime: node

# runtime-specific run attributes
main: app.js   
```
If user opts-in for named configurations, then she would need to either use `config_set_default` key either specify configuration name by using `--runconfig` :
```bash
capstan package compose --runconfig myconfig1  # if you want --run to be set during compose
capstan run --runconfig myconfig1 # normally only this would be neccessary
```
* I'd leave run config inheritance for next time.

How does this sound?
