### ISSUE TITLE
Recursive meta/run.yaml proposal

### ISSUE THREAD

**Issue by miha-plesko** [mikelangelo-project/capstan#36]
With recent [update of OSv core](https://github.com/cloudius-systems/osv/commit/c601abb21091512f967c1e4305bb64d7a20d2500) we are able to boot unikernel with `runscript` based on current environment variables i.e. command is built dynamically when `runscript` is invoked.

Below is an example of how apache.spark package works:

#### meta/run.yaml in openjdk8-zulu-compact3-with-java-beans
```yaml
runtime: native
config_set:
  java:
    bootcmd: /java.so -Xms$XMS -Xmx$XMX -cp $CLASSPATH $JVM_ARGS $MAIN $ARGS
    env:
      XMS: 512m
      XMX: 512m
      CLASSPATH: /
      JVM_ARGS: -Duser.dir=/
      MAIN: main.Hello
      ARGS:
```

#### meta/run.yaml in apache.spark
```yaml
runtime: native
config_set:
  master:
    bootcmd: /java.so -Duser.dir=/spark -Xms$XMS -Xmx$XMX -cp /spark/conf:/spark/jars/* -Dscala.usejavacp=true org.apache.spark.deploy.master.Master --host $HOST --port $PORT --webui-port $UIPORT
    env:
      XMS: 512m
      XMX: 512m
      HOST: 0.0.0.0
      PORT: 7077
      UIPORT: 8080
  worker:
    bootcmd: /java.so -Duser.dir=/spark -Xms$XMS -Xmx$XMX -cp /spark/conf:/spark/jars/* -Dscala.usejavacp=true org.apache.spark.deploy.worker.Worker $MASTER
    env:
      XMS: 512m
      XMX: 512m
      MASTER: localhost:7077
config_set_default: worker
```
Notice how bootcmd is actually a copy-paste from `openjdk8-zulu-compact3-with-java-beans` package only it sets different environment variables for it. This is what the proposal below aims to resolve.

#### meta/run.yaml in my package that uses apache.spark
One cannot make use of `meta/run.yaml` but simply run unikernel with:
```bash
$ capstan run --boot worker --env MASTER=172.16.122.3:7077
```

# Proposal
I suggest that we support recursive `meta/run.yaml` so that user will be able to make use of arbitrary config_set from arbitrary package and only provide environment variables for it. This would result in apache.spark turning into this:

#### meta/run.yaml in openjdk8-zulu-compact3-with-java-beans
```yaml
runtime: native
config_set:
  java:
    bootcmd: /java.so -Xms$XMS -Xmx$XMX -cp $CLASSPATH $JVM_ARGS $MAIN $ARGS
    env:
      XMS: 512m
      XMX: 512m
      CLASSPATH: /
      JVM_ARGS: -Duser.dir=/
      MAIN: main.Hello
      ARGS:
```
(same as before)

#### meta/run.yaml in apache.spark
```yaml
runtime: native
config_set:
  master:
    base: "openjdk8-zulu-compact3-with-java-beans:java"
    env:
      JVM_ARGS: -Duser.dir=/spark -Dscala.usejavacp=true
      MAIN: org.apache.spark.deploy.master.Master
      ARGS: --host $HOST --port $PORT --webui-port $UIPORT
      CLASSPATH: /spark/conf:/spark/jars/*
      HOST: 0.0.0.0
      PORT: 7077
      UIPORT: 8080
  worker:
    base: "openjdk8-zulu-compact3-with-java-beans:java"
    env:
      JVM_ARGS: -Duser.dir=/spark -Dscala.usejavacp=true
      MAIN: org.apache.spark.deploy.worker.Worker
      ARGS: $MASTER
      CLASSPATH: /spark/conf:/spark/jars/*
      MASTER: localhost:7077
config_set_default: worker
```
Notice how we introduce `base: "<package>:<config_set>"` and then only contextualize that specific config_set with our own environment variables.

#### meta/run.yaml in my package that uses apache.spark
```yaml
runtime: native
config_set:
  master:
    base: "apache.spark:master"
    env:
      PORT: 9000
      UIPORT: 9001
  worker:
    base: "apache.spark:worker"
    env:
      MASTER: 172.16.122.3:7077
config_set_default: worker
```
Notice how we are now able to use apache.spark on our custom ports 9000 and 9001 by default:
```bash
$ capstan run demo --boot master  # will run on 9000 and 9001
```
or specify it by ourselfs (this is already supported, so nothing surprising):
```bash
$ capstan run demo --boot master --env PORT=9998 --env UIPORT=9999
```
