### ISSUE TITLE
Porting simple Java application

### ISSUE THREAD

**Issue by acsdkquery** [mikelangelo-project/capstan#45]
I am trying to create a OSv with a simple "hello" java application..

Source:
```
VirtualBox:~/osv_java$ cat MyClass.java 
class MyClass
{
    public static void main(String[] args)
     {
       System.out.println("Hello World");
     }
}
VirtualBox:~

Compiled and created .jar files:
VirtualBox:~/osv_java$ ls
MyClass.class  MyClass.jar  MyClass.java
VirtualBox:~/osv_java$ 

Executed:
VirtualBox:~/osv_java$ java MyClass
Hello World
VirtualBox:~/osv_java$ 
```

Created a capstan package with java runtime and updated the run.yaml as below,
```
VirtualBox:~/osv_java$ cat meta/run.yaml 

runtime: java

config_set: 

   ################################################################
   ### This is one configuration set (feel free to rename it).  ###
   ################################################################
   myconfig1:
      # REQUIRED
      # Fully classified name of the main class.
      # Example value: main.Hello
      main: MyClass
      
      # REQUIRED
      # A list of paths where classes and other resources can be found.
      # Example value: classpath: 
      #                   - /
      #                   - /package1
      classpath: 
          - /MyClass.class
          - /MyClass.jar
         
      
   # Add as many named configurations as you need

# OPTIONAL
# What config_set should be used as default.
# This value can be overwritten with --runconfig argument.
config_set_default: myconfig1
VirtualBox:~/osv_java$ 
```

Composed the package:
```
VirtualBox:~/osv_java$ capstan package compose javatest
Command line will be set based on config_set_default attribute of meta/run.yaml
Resolved runtime into: java
Prepending 'java' runtime dependencies to dep list: [eu.mikelangelo-project.osv.java]
Importing javatest...
Importing into /home/carun/.capstan/repository/javatest/javatest.qemu
Uploading files to /home/carun/.capstan/repository/javatest/javatest.qemu...
Setting cmdline: --norandom --nomount --noinit /tools/mkfs.so; /tools/cpiod.so --prefix /zfs/zfs; /zfs.so set compression=off osv
Uploading files 697 / 697 [===================================================================================================] 100.00 % 1m15s
All files uploaded
Command line set to: 'runscript /run/myconfig1'
VirtualBox:~/osv_java$ 


Finally run:
VirtualBox:~/osv_java$ capstan run javatest
Created instance: javatest
OSv v0.24-370-g2b1a07e
eth0: 192.168.122.15
java.so: Starting JVM app using: io/osv/isolated/RunIsolatedJvmApp
java.so: Setting Java system classloader to IsolatingOsvSystemClassLoader and logging manager to IsolatingLogManager

VirtualBox:~/osv_java$ 
```

Image is running fine but "Hello World" is not printed, 

So,
i am not sure whether my image correctly port my sample java application.
whether i did any wrong in  classpath config in run.yaml

Kindly help on this. Thanks in advance.!
